[prep]
filters = ['F555W', 'F814W', 'F090W', 'F150W', 'F160W', 'F277W']
PSF_file = 'PSFdata.h5'
blur_psf = {F555W = 4, F814W = 5, F090W = 3.8, F150W = 3.8, F160W = 9, F277W = 9}
custom_initial_crop = 1
sigma_guess = 10
auto_crop = true
auto_crop_factor = 8 # size of each axis in units of STD of best-fit Gaussian

[core]
base_filter = 'F150W'
iter_basefit = 10
iter_scalefit = 3
fit_complex_model = false
allow_refit = false

[psf]
mask_aper_size_in_r_eff = 2.5
aperture_radius = 3
fitter_maxiters = 300
IterativePSFPhotometry_maxiters = 5
grouper_separation_in_psfsigma = 2

[aperture]
petro = 0.5
center_mask=4.0
plot=true
isophot_base_filter = 'F150W'
isophot_frac_min = 0.05
isophot_frac_max = 0.95
fit_isophot_to='sersic_modelimg'
measure_on = 'psf_sub_data'
error_on = 'psf_sub_data_error'
measure_sky_on='residual_masked'
fill_max_nan_frac=0.7
fill_replace_with='sersic_modelimg'
PSF_corr_base_filter='F090W'