[prep]
filters = ['F555W', 'F814W', 'F090W', 'F150W', 'F160W', 'F277W']
PSF_file = 'PSFdata.h5'
blur_psf = {F555W = 4, F814W = 5, F090W = 3.8, F150W = 3.8, F160W = 9, F277W = 9}
custom_initial_crop = 1
sigma_guess = 10
auto_crop = true
auto_crop_factor = 8 # size of each axis in units of STD of best-fit Gaussian

[core]
base_filter = 'F150W'
iter_basefit = 10
iter_scalefit = 3
fit_complex_model = false
allow_refit = false

[psf]
# iterative fit settings
th_min = 5
th_max = 30
th_iter = 10 # N_iteration between min and max
mask_aper_size_in_r_eff = 3.5
raise_error = false
residual_clip_sigma = 15.0 # keep this high to avoid over-masking

# finder/grouper/bkg parameters
finder_kwargs = {roundhi=1.0, roundlo=-1.0, sharplo=0.20, sharphi=1.0}
grouper_separation_in_psfsigma = 2
bkg_sigma_clip = 3.0
bkg_box_size = [10,10]
bkg_filter_size = [5,5]
localbkg_bounds_in_psfsigma = [2,5]

# Photutils PSFPhotometry parameters
PSFPhotometry_aperture_radius = 3
PSFPhotometry_fitter_maxiters = 300
PSFPhotometry_maxiters = 5
PSFPhotometry_mode = 'new'
PSFPhotometry_fit_shape = [3,3] # pixels. use small number for crowded fields
PSFPhotometry_multiprocessing = false
modelimg_render_shape = [25,25]
PSFPhotometry_group_warning_threshold = 10

# quality cuts
cuts_pos_err_max = 2 # pixels in fitted coordinates
cuts_res_cen_sigma_clip = 3.0 # -N*bkg_std < res_cen < max(N*std(res_cen), N*bkg_std)
cuts_cfit_sigma_clip = 3.0 # N-sigma for cfit
# cuts_qfit_median_factor = 2.0 # max_qfit/median(qfit)
cuts_chi2dof_median_factor = 3.0 # max_chi2dof/median(chi2dof)
cuts_pos_diff_median_factor = 2.0 # max_pos_diff/median(pos_diff)
cuts_flux_SNR_min = 1.0 # min flux_SNR

[aperture]
petro = 0.5
center_mask=4.0
plot=true
isophot_base_filter = 'F150W'
isophot_frac_min = 0.05
isophot_frac_max = 0.95
fit_isophot_to='sersic_modelimg'
measure_on = 'psf_sub_data'
error_on = 'psf_sub_data_error'
measure_sky_on='residual_masked'
fill_max_nan_frac=0.7
fill_replace_with='sersic_modelimg'
PSF_corr_base_filter='F090W'